title: "My Academic Website"
site: 
  type: "scientific"
  content: "./"
  blog: "./blog"
  output-dir: "_site"
format: 
  html: 
    toc: true
    toc-depth: 2
    number-sections: true
    theme: "cosmo"
    css: styles.css
    includes: 
      in-header: header.html
